apiVersion: v1
kind: Service
metadata:
  name: ih-prd-remote-fund-cmt-auto-webapp
  namespace: ih
  labels: {app: ih-prd-remote-fund-cmt-auto, component: webapp, env: prd}
spec:
  type: ClusterIP
  selector: {app: ih-prd-remote-fund-cmt-auto, component: webapp}
  ports:
    - {name: http, port: 80, targetPort: http, protocol: TCP}