"""initial schema

Revision ID: a814ab1a018d
Revises:
Create Date: 2026-08-06 17:53:34.257039
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a814ab1a018d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('benchmark_code', sa.String(length=32), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('language_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'FINALIZED', name='reportstatus'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('parent_report_id', sa.String(length=36), nullable=True),
    sa.Column('revision_reason', sa.String(length=500), nullable=True),
    sa.Column('finalized_document_version', sa.Integer(), nullable=True),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_product_code'), 'reports', ['product_code'], unique=False)
    op.create_table('data_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('validation_results', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('applied_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_imports_report_id'), 'data_imports', ['report_id'], unique=False)
    op.create_table('data_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source_policy', sa.String(length=30), nullable=False),
    sa.Column('mapping_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALID', 'INVALID', name='snapshotstatus'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('quality_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_snapshots_report_id'), 'data_snapshots', ['report_id'], unique=False)
    op.create_table('render_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('renderer_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_artifacts_report_id'), 'render_artifacts', ['report_id'], unique=False)
    op.create_table('render_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_render_jobs_report_id'), 'render_jobs', ['report_id'], unique=False)
    op.create_table('report_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('language_mode', sa.String(length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'version', name='uq_report_document_version')
    )
    op.create_index(op.f('ix_report_documents_report_id'), 'report_documents', ['report_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_documents_report_id'), table_name='report_documents')
    op.drop_table('report_documents')
    op.drop_index(op.f('ix_render_jobs_report_id'), table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index(op.f('ix_render_artifacts_report_id'), table_name='render_artifacts')
    op.drop_table('render_artifacts')
    op.drop_index(op.f('ix_data_snapshots_report_id'), table_name='data_snapshots')
    op.drop_table('data_snapshots')
    op.drop_index(op.f('ix_data_imports_report_id'), table_name='data_imports')
    op.drop_table('data_imports')
    op.drop_index(op.f('ix_reports_product_code'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
